### ISSUE TITLE
persistentSubscription.php stops in case of message retry

### ISSUE THREAD

**Issue by rhofland** [madkom/event-source-client#4]
Great library. 

Found an issue in a specific case when GES is retrying a message to the client. 
1. run 1 persistentSubscription.php, but comment out the ack part. 
2. add a message
3. See the message come in, then Ctrl-C the persistentSubscription.php
4. restart 1 persistentSubscription (with ack part back in), it shows Subscription confirmed:, at the exact time the GetEventStore is retrying the un-acked message, the persistentSubscription stops and exits. The message isn't handled. 
5. try restarting the persistentSubscription it will keep doing the same thing. 
6. If I start 2 persistentSubscriptions, 1 will stop and exit, the other will handle the message and keep waiting for additional messages. If I restart the stopped one it will now work. 

Thanks.

**Comment by JurJean** [comment]
If I understand it correctly - this is an issue when an exception is not catched, and the message is never acked / nacked?

**Comment by rhofland** [comment]
Right, the test was to see what happened when persistentSubscription.php died before a ack/nack was sent. Since there was no ack/nack for that message, GES will retry the message. When I restarted the persistentSubscription.php it would connect, GES would retry the message, immediately persistentSubscription.php dies without Exception.

**Comment by rhofland** [comment]
FYI, https://groups.google.com/forum/#!topic/event-store/4MPSphUaPXg

**Comment by JurJean** [comment]
Wow, very cool dude! I wonder if it solves the issue that I experienced when setting the maximum in-flight messages too high. If it doesn't, it's probably somewhere in the same code.

I'm curious, great job!

**Comment by dgafka** [comment]
Merged.
